language: python
python: 3.7
install:
  - pip install -e .
  - pip install -r tests/tests.req
script:
  coverage run --source skycrawler -m pytest
after_success:
  coveralls

notifications:
  email: false
