language: python
python:
  - "3.5"
install:
- pip install -r skycrawler.req -r tests/tests.req
script:
 coverage run --source skycrawler -m pytest
after_success:
  coveralls
notifications:
  email: false
