version: '3.1'

services:

  skycrawler_back:
    image: waxisien/skycrawler-back:test
    environment:
        - SKYCRAWLER_DB=/etc/skyscraper.db
    volumes:
      - /opt/skycrawler/skyscraper.db:/etc/skyscraper.db

  skycrawler_front:
    image: waxisien/skycrawler-front:test
    ports:
      - 80:80
    depends_on:
      - skycrawler_back
